name: ci
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Run | Lint
        run: pnpm run lint

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Run | Format
        run: pnpm run format:check

  typecheck:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Run | Typecheck
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Run | Build
        run: pnpm run build
